import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import torch
import torch.nn as nn
import torch.optim as optim

# Step 1: Load the original dataset with 'quality' column
data_path = 'winequality-white-corrected.csv'
data = pd.read_csv(data_path)

# Separate features and the 'quality' column
features = data.drop(columns=['quality']).values
quality = data['quality'].values

# Normalize features and scale quality
scaler = MinMaxScaler()
features_scaled = scaler.fit_transform(features)
quality_min, quality_max = quality.min(), quality.max()
quality_scaled = (quality - quality_min) / (quality_max - quality_min)
quality_tensor = torch.tensor(quality_scaled, dtype=torch.float32).view(-1, 1)

# Step 2: Define the Conditional GAN (cGAN) Model
class Generator(nn.Module):
    def __init__(self, input_dim, quality_dim, output_dim):
        super(Generator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim + quality_dim, 256),
            nn.LeakyReLU(0.2),
            nn.Linear(256, 512),
            nn.LeakyReLU(0.2),
            nn.Linear(512, 256),
            nn.LeakyReLU(0.2),
            nn.Linear(256, output_dim),
            nn.Tanh()
        )

    def forward(self, noise, quality):
        x = torch.cat([noise, quality], dim=1)
        return self.model(x)

class Discriminator(nn.Module):
    def __init__(self, input_dim, quality_dim):
        super(Discriminator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim + quality_dim, 512),
            nn.LeakyReLU(0.2),
            nn.Linear(512, 256),
            nn.LeakyReLU(0.2),
            nn.Linear(256, 1),
            nn.Sigmoid()
        )

    def forward(self, features, quality):
        x = torch.cat([features, quality], dim=1)
        return self.model(x)

# Model parameters
latent_dim = 100
feature_dim = features_scaled.shape[1]
quality_dim = 1

# Instantiate generator and discriminator
generator = Generator(latent_dim, quality_dim, feature_dim)
discriminator = Discriminator(feature_dim, quality_dim)

# Optimizers and loss function
optimizer_G = optim.Adam(generator.parameters(), lr=0.0001, betas=(0.5, 0.999))
optimizer_D = optim.Adam(discriminator.parameters(), lr=0.0004, betas=(0.5, 0.999))
adversarial_loss = nn.BCELoss()

# Convert data to PyTorch tensors
features_tensor = torch.tensor(features_scaled, dtype=torch.float32)

# Step 3: Train the cGAN
epochs = 100000
batch_size = 64
real_label = 0.9  # Label smoothing
fake_label = 0.1  # Label smoothing

for epoch in range(epochs):
    # Train Discriminator
    for _ in range(3):  # Training ratio: 3 steps for D, 1 step for G
        # Sample real data
        idx = np.random.randint(0, features_scaled.shape[0], batch_size)
        real_features = features_tensor[idx]
        real_quality = quality_tensor[idx]
        
        # Labeling real and fake batches with label smoothing
        valid = torch.full((batch_size, 1), real_label)
        fake = torch.full((batch_size, 1), fake_label)

        # Train on real data
        optimizer_D.zero_grad()
        real_loss = adversarial_loss(discriminator(real_features, real_quality), valid)

        # Generate fake data
        noise = torch.randn(batch_size, latent_dim)
        gen_features = generator(noise, real_quality)

        # Train on fake data
        fake_loss = adversarial_loss(discriminator(gen_features.detach(), real_quality), fake)
        
        # Total discriminator loss and optimization
        d_loss = (real_loss + fake_loss) / 2
        d_loss.backward()
        optimizer_D.step()

    # Train Generator
    optimizer_G.zero_grad()
    noise = torch.randn(batch_size, latent_dim)
    gen_features = generator(noise, real_quality)
    g_loss = adversarial_loss(discriminator(gen_features, real_quality), valid)
    g_loss.backward()
    optimizer_G.step()

    # Print progress
    if epoch % 100 == 0:
        print(f"Epoch [{epoch}/{epochs}] - D Loss: {d_loss.item()}, G Loss: {g_loss.item()}")

# Step 4: Generate synthetic data based on specified quality values
# Load the synthetic dataset generated by the GAN (without 'quality')
synthetic_data_path = 'synthetic_winequality_features6.csv'
synthetic_data = pd.read_csv(synthetic_data_path)

# Choose desired quality values based on the distribution in the original data
num_synthetic_samples = 4898
sampled_quality = np.random.choice(quality_scaled, num_synthetic_samples).reshape(-1, 1)
sampled_quality_tensor = torch.tensor(sampled_quality, dtype=torch.float32)

# Generate synthetic features based on sampled quality values
noise = torch.randn(num_synthetic_samples, latent_dim)
with torch.no_grad():
    generated_features = generator(noise, sampled_quality_tensor)

# Transform generated features and quality back to original scale
generated_features = scaler.inverse_transform(generated_features.numpy())
generated_quality = (sampled_quality * (quality_max - quality_min) + quality_min).astype(int).flatten()

# Combine generated features and quality into a DataFrame
synthetic_data_with_quality = pd.DataFrame(generated_features, columns=synthetic_data.columns)
synthetic_data_with_quality['quality'] = generated_quality

# Save the augmented synthetic dataset to a new CSV file
synthetic_data_with_quality.to_csv('cgan_white_wine_7.csv', index=False)

print("Synthetic data with generated 'quality' saved to 'synthetic_winequality_with_quality.csv'")
